// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR5dsOU5h-LRxB1N1fm9w0sUXOtdC1axM',
    appId: '1:594951275547:web:29ad0512fc000d06b964be',
    messagingSenderId: '594951275547',
    projectId: 'seldura-chat-app-demo',
    authDomain: 'seldura-chat-app-demo.firebaseapp.com',
    storageBucket: 'seldura-chat-app-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNg8RqjR23r_fqqIRrCk-s456wQAROtCA',
    appId: '1:594951275547:android:bff683ec731c08a9b964be',
    messagingSenderId: '594951275547',
    projectId: 'seldura-chat-app-demo',
    storageBucket: 'seldura-chat-app-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8FHvA9Sqoit2yZEBwKPdK4f7731KzH0',
    appId: '1:594951275547:ios:802fb74df0eb5aa8b964be',
    messagingSenderId: '594951275547',
    projectId: 'seldura-chat-app-demo',
    storageBucket: 'seldura-chat-app-demo.appspot.com',
    iosClientId: '594951275547-14lfr0t67c1bljhp93m6a2vhncf3920q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemo',
  );
}
